In [1]:
# एक DataFrame बनाओ जिसमें 3 students के नाम, उनकी age और marks हों। फिर age का average निकालो।

import pandas as pd 
data=pd.DataFrame({
    'name' :['Yunsu','Neha','Seha'],
    'age':[23,24,25],
    'marks':[90,80,78]
})

In [2]:
data

    name  age  marks
0  Yunsu   23     90
1   Neha   24     80
2   Seha   25     78

In [3]:
data['age'].mean()

np.float64(24.0)

In [4]:
data['name'].max()

'Yunsu'

In [7]:
# ✅ sabse jyada marks
data.loc[data['marks'].idxmax(),'name']

'Yunsu'

In [9]:
# 80 se jyada marks
data[data['marks']>80][['name','marks']]

    name  marks
0  Yunsu     90

In [ ]:
# DataFrame में total कितने students हैं, count निकालो।

# Average marks निकालो।

# सबसे ज़्यादा age वाले student का नाम निकालो।

# जिनकी age 23 से ज़्यादा है, उनके नाम और marks दिखाओ।

# Marks को descending order में sort करो।

In [12]:
# DataFrame में total कितने students हैं, count निकालो।

data['name'].count()

np.int64(3)

In [13]:
# Average marks निकालो।
data['marks'].mean()

np.float64(82.66666666666667)

In [28]:
# सबसे ज़्यादा age वाले student का नाम निकालो।

data.loc[data['age'].idxmax(),'name']

'Seha'

In [29]:
# जिनकी age 23 से ज़्यादा है, उनके नाम और marks दिखाओ।
data[data['age']>23][['name','marks']]

   name  marks
1  Neha     80
2  Seha     78

In [30]:
# Marks को descending order में sort करो।

data['marks'].sort_values(ascending=False)

0    90
1    80
2    78
Name: marks, dtype: int64

In [32]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [33]:
df

     PassengerId  Survived  Pclass                                               Name     Sex  ...  Parch            Ticket     Fare Cabin  Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  ...      0         A/5 21171   7.2500   NaN         S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  ...      0          PC 17599  71.2833   C85         C
2              3         1       3                             Heikkinen, Miss. Laina  female  ...      0  STON/O2. 3101282   7.9250   NaN         S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  ...      0            113803  53.1000  C123         S
4              5         0       3                           Allen, Mr. William Henry    male  ...      0            373450   8.0500   NaN         S
..           ...       ...     ...                                                ...     ...  ...    ...               ...      ...   ...       ...
886          887         0       2                              Montvila, Rev. Juozas    male  ...      0            211536  13.0000   NaN         S
887          888         1       1                       Graham, Miss. Margaret Edith  female  ...      0            112053  30.0000   B42         S
888          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female  ...      2        W./C. 6607  23.4500   NaN         S
889          890         1       1                              Behr, Mr. Karl Howell    male  ...      0            111369  30.0000  C148         C
890          891         0       3                                Dooley, Mr. Patrick    male  ...      0            370376   7.7500   NaN         Q

[891 rows x 12 columns]

In [34]:
# Dataset में total कितने passengers हैं?
df['PassengerId'].count()

np.int64(891)

In [35]:
len(df['PassengerId'])

891

In [49]:
# Dataset में कितने columns हैं और उनके नाम क्या हैं?

len(df.columns)

12

In [50]:
df.columns.tolist()

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [56]:
# Survived column में कितने लोग survived हुए और कितने नहीं?
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [57]:
# Sex column में कितने male और female passengers हैं?

df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [58]:
# Pclass column में कितने लोग हैं (1st, 2nd, 3rd class)?

df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [63]:
# 2. Selection / Filtering

# जिनकी age 18 से कम है, उनके नाम और age दिखाओ।abs

df[df['Age']<18][['Name','Age']]

                                        Name   Age
7             Palsson, Master. Gosta Leonard   2.0
9        Nasser, Mrs. Nicholas (Adele Achem)  14.0
10           Sandstrom, Miss. Marguerite Rut   4.0
14      Vestrom, Miss. Hulda Amanda Adolfina  14.0
16                      Rice, Master. Eugene   2.0
..                                       ...   ...
850  Andersson, Master. Sigvard Harald Elias   4.0
852                  Boulos, Miss. Nourelain   9.0
853                Lines, Miss. Mary Conover  16.0
869          Johnson, Master. Harold Theodor   4.0
875         Najib, Miss. Adele Kiamie "Jane"  15.0

[113 rows x 2 columns]

In [84]:
# Pclass 1 में कितने लोग थे और उनमें से कितने survived हुए?


pc=df[df['Pclass']==1 ]
len(pc)

216

In [85]:
pc['Survived'].value_counts()

Survived
1    136
0     80
Name: count, dtype: int64

In [80]:
# Fare 100 से ज़्यादा देने वाले passengers के नाम और fare दिखाओ।

df[df['Fare']>100][['Name','Fare']]

                                                  Name      Fare
27                      Fortune, Mr. Charles Alexander  263.0000
31      Spencer, Mrs. William Augustus (Marie Eugenie)  146.5208
88                          Fortune, Miss. Mabel Helen  263.0000
118                           Baxter, Mr. Quigg Edmond  247.5208
195                               Lurette, Miss. Elise  146.5208
215                            Newell, Miss. Madeleine  113.2750
258                                   Ward, Miss. Anna  512.3292
268      Graham, Mrs. William Thompson (Edith Junkins)  153.4625
269                             Bissette, Miss. Amelia  135.6333
297                       Allison, Miss. Helen Loraine  151.5500
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208
305                     Allison, Master. Hudson Trevor  151.5500
306                            Fleming, Miss. Margaret  110.8833
307  Penasco y Castellana, Mrs. Victor de Satode (M...  108.9000
311                         Ryerson, Miss. Emily Borie  262.3750
318                           Wick, Miss. Mary Natalie  164.8667
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  134.5000
325                           Young, Miss. Marie Grice  135.6333
332                          Graham, Mr. George Edward  153.4625
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  133.6500
337                    Burns, Miss. Elizabeth Margaret  134.5000
341                     Fortune, Miss. Alice Elizabeth  263.0000
373                                Ringhini, Mr. Sante  135.6333
377                          Widener, Mr. Harry Elkins  211.5000
380                              Bidois, Miss. Rosalie  227.5250
390                         Carter, Mr. William Ernest  120.0000
393                             Newell, Miss. Marjorie  113.2750
435                          Carter, Miss. Lucile Polk  120.0000
438                                  Fortune, Mr. Mark  263.0000
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  151.5500
505         Penasco y Castellana, Mr. Victor de Satode  108.9000
527                                 Farthing, Mr. John  221.7792
537                                LeRoy, Miss. Bertha  106.4250
544                         Douglas, Mr. Walter Donald  106.4250
550                        Thayer, Mr. John Borland Jr  110.8833
557                                Robbins, Mr. Victor  227.5250
581  Thayer, Mrs. John Borland (Marian Longstreth M...  110.8833
609                          Shutes, Miss. Elizabeth W  153.4625
659                         Newell, Mr. Arthur Webster  113.2750
660                      Frauenthal, Dr. Henry William  133.6500
679                 Cardeza, Mr. Thomas Drake Martinez  512.3292
689                  Madill, Miss. Georgette Alexandra  211.3375
698                           Thayer, Mr. John Borland  110.8833
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  227.5250
708                               Cleaver, Miss. Alice  151.5500
716                      Endres, Miss. Caroline Louise  227.5250
730                      Allen, Miss. Elisabeth Walton  211.3375
737                             Lesurer, Mr. Gustave J  512.3292
742              Ryerson, Miss. Susan Parker "Suzette"  262.3750
763          Carter, Mrs. William Ernest (Lucile Polk)  120.0000
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  211.3375
802                Carter, Master. William Thornton II  120.0000
856         Wick, Mrs. George Dennick (Mary Hitchcock)  164.8667

In [109]:
# Female passengers जिनकी age 30 से ज़्यादा है, उनके नाम और Pclass दिखाओ।


df[(df['Sex']=='female')&(df['Age']>30)][['Name','Pclass']]

                                                  Name  Pclass
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
11                            Bonnell, Miss. Elizabeth       1
15                    Hewlett, Mrs. (Mary D Kingcome)        2
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...       3
..                                                 ...     ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...       1
865                           Bystrom, Mrs. (Karolina)       2
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)       1
885               Rice, Mrs. William (Margaret Norton)       3

[103 rows x 2 columns]

In [117]:
# Male passengers जो survived हुए, उनके नाम और age दिखाओ।

df[(df['Sex']=='male')&(df['Survived']==1)][['Name','Age']]

                                Name   Age
17      Williams, Mr. Charles Eugene   NaN
21             Beesley, Mr. Lawrence  34.0
23      Sloper, Mr. William Thompson  28.0
36                  Mamee, Mr. Hanna   NaN
55                 Woolner, Mr. Hugh   NaN
..                               ...   ...
838                  Chip, Mr. Chang  32.0
839             Marechal, Mr. Pierre   NaN
857           Daly, Mr. Peter Denis   51.0
869  Johnson, Master. Harold Theodor   4.0
889            Behr, Mr. Karl Howell  26.0

[109 rows x 2 columns]

In [121]:
# Embarked column में "C" से embarked passengers के नाम दिखाओ।

df[df['Embarked']=='C']['Name']

                                                  Name Embarked
1    Cumings, Mrs. John Bradley (Florence Briggs Th...        C
9                  Nasser, Mrs. Nicholas (Adele Achem)        C
19                             Masselmani, Mrs. Fatima        C
26                             Emir, Mr. Farred Chehab        C
30                            Uruchurtu, Don. Manuel E        C
..                                                 ...      ...
866                       Duran y More, Miss. Asuncion        C
874              Abelson, Mrs. Samuel (Hannah Wizosky)        C
875                   Najib, Miss. Adele Kiamie "Jane"        C
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)        C
889                              Behr, Mr. Karl Howell        C

[168 rows x 2 columns]

In [124]:
# SibSp > 2 वाले passengers के नाम और age दिखाओ।

df[df['SibSp']>2][['Name','Age','SibSp']]

                                                  Name   Age  SibSp
7                       Palsson, Master. Gosta Leonard   2.0      3
16                                Rice, Master. Eugene   2.0      4
24                       Palsson, Miss. Torborg Danira   8.0      3
27                      Fortune, Mr. Charles Alexander  19.0      3
50                          Panula, Master. Juha Niilo   7.0      4
59                  Goodwin, Master. William Frederick  11.0      5
63                               Skoog, Master. Harald   4.0      3
68                     Andersson, Miss. Erna Alexandra  17.0      4
71                          Goodwin, Miss. Lillian Amy  16.0      5
85   Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  33.0      3
88                          Fortune, Miss. Mabel Helen  23.0      3
119                  Andersson, Miss. Ellis Anna Maria   2.0      4
159                         Sage, Master. Thomas Henry   NaN      8
164                       Panula, Master. Eino Viljami   1.0      4
171                               Rice, Master. Arthur   4.0      4
176                      Lefebre, Master. Henry Forbes   NaN      3
180                       Sage, Miss. Constance Gladys   NaN      8
182              Asplund, Master. Clarence Gustaf Hugo   9.0      4
201                                Sage, Mr. Frederick   NaN      8
229                            Lefebre, Miss. Mathilde   NaN      3
233                     Asplund, Miss. Lillian Gertrud   5.0      4
261                  Asplund, Master. Edvin Rojj Felix   3.0      4
266                          Panula, Mr. Ernesti Arvid  16.0      4
278                                 Rice, Master. Eric   7.0      4
324                           Sage, Mr. George John Jr   NaN      8
341                     Fortune, Miss. Alice Elizabeth  24.0      3
374                         Palsson, Miss. Stina Viola   3.0      3
386                    Goodwin, Master. Sidney Leonard   1.0      5
409                                 Lefebre, Miss. Ida   NaN      3
480                     Goodwin, Master. Harold Victor   9.0      5
485                             Lefebre, Miss. Jeannie   NaN      3
541               Andersson, Miss. Ingeborg Constanzia   9.0      4
542                  Andersson, Miss. Sigrid Elisabeth  11.0      4
634                                 Skoog, Miss. Mabel   9.0      3
642                      Skoog, Miss. Margit Elizabeth   2.0      3
683                        Goodwin, Mr. Charles Edward  14.0      5
686                           Panula, Mr. Jaako Arnold  14.0      4
726        Renouf, Mrs. Peter Henry (Lillian Jefferys)  30.0      3
787                          Rice, Master. George Hugh   8.0      4
792                            Sage, Miss. Stella Anna   NaN      8
813                 Andersson, Miss. Ebba Iris Alfrida   6.0      4
819                       Skoog, Master. Karl Thorsten  10.0      3
824                       Panula, Master. Urho Abraham   2.0      4
846                           Sage, Mr. Douglas Bullen   NaN      8
850            Andersson, Master. Sigvard Harald Elias   4.0      4
863                  Sage, Miss. Dorothy Edith "Dolly"   NaN      8

In [126]:
# 3. Aggregation / Statistics

# Average age कितनी है?

df['Age'].mean()

np.float64(29.69911764705882)

In [140]:
# Maximum और minimum age कौन-कौन है?
df[df['Age']==df['Age'].max()][['Name','Age']]

                                     Name   Age
630  Barkworth, Mr. Algernon Henry Wilson  80.0

In [141]:
df[df['Age']==df['Age'].min()][['Name','Age']]

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42

In [142]:
# Average fare कितनी है?

df['Fare'].mean()

np.float64(32.204207968574636)

In [144]:
# सबसे ज़्यादा Fare देने वाले passenger का नाम और fare कौन सा है?

df[df['Fare']==df['Fare'].max()][['Name','Fare']]

                                   Name      Fare
258                    Ward, Miss. Anna  512.3292
679  Cardeza, Mr. Thomas Drake Martinez  512.3292
737              Lesurer, Mr. Gustave J  512.3292

In [165]:
# Survived के हिसाब से average age और fare निकालो।
df.groupby('Survived')[['Age','Fare']].mean()

                Age       Fare
Survived
0         30.626179  22.117887
1         28.343690  48.395408

In [167]:
df.groupby(['Pclass','Sex','Survived'])['Fare'].mean()

Pclass  Sex     Survived
1       female  0           110.604167
                1           105.978159
        male    0            62.894910
                1            74.637320
2       female  0            18.250000
                1            22.288989
        male    0            19.488965
                1            21.095100
3       female  0            19.773093
                1            12.464526
        male    0            12.204469
                1            15.579696
Name: Fare, dtype: float64

In [168]:
# Pclass के हिसाब से average fare निकालो।
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [169]:
# Sex के हिसाब से average age निकालो।
df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [177]:
# Age के हिसाब से passengers को ascending order में sort करो।
# df.sort_values(by='Age',ascending=True)

In [172]:
# Total family members (SibSp + Parch) के हिसाब से सबसे बड़ा family कौन है?
df['family']=df['SibSp']+df['Parch']
df[df['family']==df['family'].max()][['Name','family','SibSp','Parch']]

                                  Name  family  SibSp  Parch
159         Sage, Master. Thomas Henry      10      8      2
180       Sage, Miss. Constance Gladys      10      8      2
201                Sage, Mr. Frederick      10      8      2
324           Sage, Mr. George John Jr      10      8      2
792            Sage, Miss. Stella Anna      10      8      2
846           Sage, Mr. Douglas Bullen      10      8      2
863  Sage, Miss. Dorothy Edith "Dolly"      10      8      2

In [178]:
df.groupby('Survived')['Fare'].mean()

Survived
0    22.117887
1    48.395408
Name: Fare, dtype: float64

In [179]:
df[df['Survived']==1]['Fare'].mean()

np.float64(48.39540760233918)

In [182]:
# 4. Sorting / Indexing

# Age के हिसाब से passengers को ascending order में sort करो
df.sort_values(by='Age', ascending=True )

     PassengerId  Survived  Pclass                                      Name     Sex   Age  ...  Parch      Ticket     Fare  Cabin Embarked family
803          804         1       3           Thomas, Master. Assad Alexander    male  0.42  ...      1        2625   8.5167    NaN        C      1
755          756         1       2                 Hamalainen, Master. Viljo    male  0.67  ...      1      250649  14.5000    NaN        S      2
644          645         1       3                    Baclini, Miss. Eugenie  female  0.75  ...      1        2666  19.2583    NaN        C      3
469          470         1       3             Baclini, Miss. Helene Barbara  female  0.75  ...      1        2666  19.2583    NaN        C      3
78            79         1       2             Caldwell, Master. Alden Gates    male  0.83  ...      2      248738  29.0000    NaN        S      2
..           ...       ...     ...                                       ...     ...   ...  ...    ...         ...      ...    ...      ...    ...
859          860         0       3                          Razi, Mr. Raihed    male   NaN  ...      0        2629   7.2292    NaN        C      0
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"  female   NaN  ...      2    CA. 2343  69.5500    NaN        S     10
868          869         0       3               van Melkebeke, Mr. Philemon    male   NaN  ...      0      345777   9.5000    NaN        S      0
878          879         0       3                        Laleff, Mr. Kristo    male   NaN  ...      0      349217   7.8958    NaN        S      0
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"  female   NaN  ...      2  W./C. 6607  23.4500    NaN        S      3

[891 rows x 13 columns]

In [183]:
# Fare के हिसाब से top 5 expensive tickets दिखाओ।
df.sort_values(by='Fare',ascending=False).head(5)

     PassengerId  Survived  Pclass                                Name     Sex   Age  ...  Parch    Ticket      Fare        Cabin Embarked family
258          259         1       1                    Ward, Miss. Anna  female  35.0  ...      0  PC 17755  512.3292          NaN        C      0
737          738         1       1              Lesurer, Mr. Gustave J    male  35.0  ...      0  PC 17755  512.3292         B101        C      0
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez    male  36.0  ...      1  PC 17755  512.3292  B51 B53 B55        C      1
88            89         1       1          Fortune, Miss. Mabel Helen  female  23.0  ...      2     19950  263.0000  C23 C25 C27        S      5
27            28         0       1      Fortune, Mr. Charles Alexander    male  19.0  ...      2     19950  263.0000  C23 C25 C27        S      5

[5 rows x 13 columns]

In [187]:
# Name alphabetically sort करो।
df.sort_values(by='Name',ascending=True)['Name']

845                      Abbing, Mr. Anthony
746              Abbott, Mr. Rossmore Edward
279         Abbott, Mrs. Stanton (Rosa Hunt)
308                      Abelson, Mr. Samuel
874    Abelson, Mrs. Samuel (Hannah Wizosky)
                       ...
286                  de Mulder, Mr. Theodore
282                de Pelsmaeker, Mr. Alfons
361                del Carlo, Mr. Sebastiano
153          van Billiard, Mr. Austin Blyler
868              van Melkebeke, Mr. Philemon
Name: Name, Length: 891, dtype: object

In [188]:
# Survived column के हिसाब से descending order में sort करो।
df.sort_values(by='Survived',ascending=False)

     PassengerId  Survived  Pclass                                               Name     Sex  ...    Ticket      Fare  Cabin Embarked  family
445          446         1       1                          Dodge, Master. Washington    male  ...     33638   81.8583    A34        S       2
319          320         1       1  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  female  ...     16966  134.5000    E34        C       2
334          335         1       1  Frauenthal, Mrs. Henry William (Clara Heinshei...  female  ...  PC 17611  133.6500    NaN        S       1
330          331         1       3                                 McCoy, Miss. Agnes  female  ...    367226   23.2500    NaN        Q       2
329          330         1       1                       Hippach, Miss. Jean Gertrude  female  ...    111361   57.9792    B18        C       1
..           ...       ...     ...                                                ...     ...  ...       ...       ...    ...      ...     ...
365          366         0       3                     Adahl, Mr. Mauritz Nils Martin    male  ...    C 7076    7.2500    NaN        S       0
371          372         0       3                          Wiklund, Mr. Jakob Alfred    male  ...   3101267    6.4958    NaN        S       1
372          373         0       3                         Beavan, Mr. William Thomas    male  ...    323951    8.0500    NaN        S       0
373          374         0       1                                Ringhini, Mr. Sante    male  ...  PC 17760  135.6333    NaN        C       0
890          891         0       3                                Dooley, Mr. Patrick    male  ...    370376    7.7500    NaN        Q       0

[891 rows x 13 columns]

In [191]:
# PassengerId को index बनाओ और उसी के हिसाब से rows access करो।
df.set_index('PassengerId')

             Survived  Pclass                                               Name     Sex   Age  ...            Ticket     Fare Cabin  Embarked family
PassengerId                                                                                     ...
1                   0       3                            Braund, Mr. Owen Harris    male  22.0  ...         A/5 21171   7.2500   NaN         S      1
2                   1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  ...          PC 17599  71.2833   C85         C      1
3                   1       3                             Heikkinen, Miss. Laina  female  26.0  ...  STON/O2. 3101282   7.9250   NaN         S      0
4                   1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  ...            113803  53.1000  C123         S      1
5                   0       3                           Allen, Mr. William Henry    male  35.0  ...            373450   8.0500   NaN         S      0
...               ...     ...                                                ...     ...   ...  ...               ...      ...   ...       ...    ...
887                 0       2                              Montvila, Rev. Juozas    male  27.0  ...            211536  13.0000   NaN         S      0
888                 1       1                       Graham, Miss. Margaret Edith  female  19.0  ...            112053  30.0000   B42         S      0
889                 0       3           Johnston, Miss. Catherine Helen "Carrie"  female   NaN  ...        W./C. 6607  23.4500   NaN         S      3
890                 1       1                              Behr, Mr. Karl Howell    male  26.0  ...            111369  30.0000  C148         C      0
891                 0       3                                Dooley, Mr. Patrick    male  32.0  ...            370376   7.7500   NaN         Q      0

[891 rows x 12 columns]

In [193]:
# Age के हिसाब से descending order में top 10 passengers दिखाओ।
df.sort_values(by='Age',ascending=False).head(10)

     PassengerId  Survived  Pclass                                  Name   Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  family
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson  male  80.0      0      0       27042  30.0000   A23        S       0
851          852         0       3                   Svensson, Mr. Johan  male  74.0      0      0      347060   7.7750   NaN        S       0
493          494         0       1               Artagaveytia, Mr. Ramon  male  71.0      0      0    PC 17609  49.5042   NaN        C       0
96            97         0       1             Goldschmidt, Mr. George B  male  71.0      0      0    PC 17754  34.6542    A5        C       0
116          117         0       3                  Connors, Mr. Patrick  male  70.5      0      0      370369   7.7500   NaN        Q       0
672          673         0       2           Mitchell, Mr. Henry Michael  male  70.0      0      0  C.A. 24580  10.5000   NaN        S       0
745          746         0       1          Crosby, Capt. Edward Gifford  male  70.0      1      1   WE/P 5735  71.0000   B22        S       2
33            34         0       2                 Wheadon, Mr. Edward H  male  66.0      0      0  C.A. 24579  10.5000   NaN        S       0
54            55         0       1        Ostby, Mr. Engelhart Cornelius  male  65.0      0      1      113509  61.9792   B30        C       1
280          281         0       3                      Duane, Mr. Frank  male  65.0      0      0      336439   7.7500   NaN        Q       0

In [ ]:
df.sort_values(by='Name', ascending=False)

In [ ]:
df.sort_values(by='Survived', ascending=False)

In [198]:
# Age और Fare दोनों के हिसाब से sort करो, 
# Age descending और Fare ascending।
df.sort_values(by=['Age','Fare'],ascending=[False,True])

     PassengerId  Survived  Pclass                                               Name     Sex  ...    Ticket      Fare  Cabin Embarked  family
630          631         1       1               Barkworth, Mr. Algernon Henry Wilson    male  ...     27042   30.0000    A23        S       0
851          852         0       3                                Svensson, Mr. Johan    male  ...    347060    7.7750    NaN        S       0
96            97         0       1                          Goldschmidt, Mr. George B    male  ...  PC 17754   34.6542     A5        C       0
493          494         0       1                            Artagaveytia, Mr. Ramon    male  ...  PC 17609   49.5042    NaN        C       0
116          117         0       3                               Connors, Mr. Patrick    male  ...    370369    7.7500    NaN        Q       0
..           ...       ...     ...                                                ...     ...  ...       ...       ...    ...      ...     ...
306          307         1       1                            Fleming, Miss. Margaret  female  ...     17421  110.8833    NaN        C       0
334          335         1       1  Frauenthal, Mrs. Henry William (Clara Heinshei...  female  ...  PC 17611  133.6500    NaN        S       1
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female  ...  PC 17569  146.5208    B78        C       1
527          528         0       1                                 Farthing, Mr. John    male  ...  PC 17483  221.7792    C95        S       0
557          558         0       1                                Robbins, Mr. Victor    male  ...  PC 17757  227.5250    NaN        C       0

[891 rows x 13 columns]

In [202]:
# PassengerId को index बनाओ और PassengerId = 15 वाला row access करो।
df.set_index('PassengerId')

             Survived  Pclass                                               Name     Sex   Age  ...            Ticket     Fare Cabin  Embarked family
PassengerId                                                                                     ...
1                   0       3                            Braund, Mr. Owen Harris    male  22.0  ...         A/5 21171   7.2500   NaN         S      1
2                   1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  ...          PC 17599  71.2833   C85         C      1
3                   1       3                             Heikkinen, Miss. Laina  female  26.0  ...  STON/O2. 3101282   7.9250   NaN         S      0
4                   1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  ...            113803  53.1000  C123         S      1
5                   0       3                           Allen, Mr. William Henry    male  35.0  ...            373450   8.0500   NaN         S      0
...               ...     ...                                                ...     ...   ...  ...               ...      ...   ...       ...    ...
887                 0       2                              Montvila, Rev. Juozas    male  27.0  ...            211536  13.0000   NaN         S      0
888                 1       1                       Graham, Miss. Margaret Edith  female  19.0  ...            112053  30.0000   B42         S      0
889                 0       3           Johnston, Miss. Catherine Helen "Carrie"  female   NaN  ...        W./C. 6607  23.4500   NaN         S      3
890                 1       1                              Behr, Mr. Karl Howell    male  26.0  ...            111369  30.0000  C148         C      0
891                 0       3                                Dooley, Mr. Patrick    male  32.0  ...            370376   7.7500   NaN         Q      0

[891 rows x 12 columns]

In [203]:
df.loc[15]

PassengerId                                  16
Survived                                      1
Pclass                                        2
Name           Hewlett, Mrs. (Mary D Kingcome)
Sex                                      female
Age                                        55.0
SibSp                                         0
Parch                                         0
Ticket                                   248706
Fare                                       16.0
Cabin                                       NaN
Embarked                                      S
family                                        0
Name: 15, dtype: object

In [213]:
# Age > 30 और Sex = 'female' वाले passengers दिखाओ।
df[(df['Sex']=='female')&(df['Age']>30)]

     PassengerId  Survived  Pclass                                               Name     Sex  ...    Ticket     Fare  Cabin Embarked  family
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  ...  PC 17599  71.2833    C85        C       1
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  ...    113803  53.1000   C123        S       1
11            12         1       1                           Bonnell, Miss. Elizabeth  female  ...    113783  26.5500   C103        S       0
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female  ...    248706  16.0000    NaN        S       0
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  ...    345763  18.0000    NaN        S       1
..           ...       ...     ...                                                ...     ...  ...       ...      ...    ...      ...     ...
862          863         1       1  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  ...     17466  25.9292    D17        S       0
865          866         1       2                           Bystrom, Mrs. (Karolina)  female  ...    236852  13.0000    NaN        S       0
871          872         1       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  ...     11751  52.5542    D35        S       2
879          880         1       1      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  ...     11767  83.1583    C50        C       1
885          886         0       3               Rice, Mrs. William (Margaret Norton)  female  ...    382652  29.1250    NaN        Q       5

[103 rows x 13 columns]

In [ ]:
# SibSp + Parch करके family size वाला column बनाओ और सबसे बड़ी 
# family वाला row निकालो।

In [215]:
df['fam']=df['SibSp']+df['Parch']
df[df['fam']==df['fam'].max()]

     PassengerId  Survived  Pclass                               Name     Sex  Age  SibSp  Parch    Ticket   Fare Cabin Embarked  family  fam
159          160         0       3         Sage, Master. Thomas Henry    male  NaN      8      2  CA. 2343  69.55   NaN        S      10   10
180          181         0       3       Sage, Miss. Constance Gladys  female  NaN      8      2  CA. 2343  69.55   NaN        S      10   10
201          202         0       3                Sage, Mr. Frederick    male  NaN      8      2  CA. 2343  69.55   NaN        S      10   10
324          325         0       3           Sage, Mr. George John Jr    male  NaN      8      2  CA. 2343  69.55   NaN        S      10   10
792          793         0       3            Sage, Miss. Stella Anna  female  NaN      8      2  CA. 2343  69.55   NaN        S      10   10
846          847         0       3           Sage, Mr. Douglas Bullen    male  NaN      8      2  CA. 2343  69.55   NaN        S      10   10
863          864         0       3  Sage, Miss. Dorothy Edith "Dolly"  female  NaN      8      2  CA. 2343  69.55   NaN        S      10   10

In [218]:
# 5. Creating / Modifying Columns


# SibSp और Parch मिलाकर total family members वाला column बनाओ।
df['Total_fam']=df['SibSp']+df['Parch']
df['Total_fam']

0      1
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    3
889    0
890    0
Name: Total_fam, Length: 891, dtype: int64

In [221]:
# Age < 18 वाले passengers के लिए Child column बनाओ, जो True/False दिखाए।
df['child']=df['Age']<18
df['child']

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: child, Length: 891, dtype: bool

In [224]:
# Fare > 50 वाले passengers के लिए Expensive column बनाओ।
df['Expensive']=df['Fare']<50
df['Expensive']
df

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887     True
888     True
889     True
890     True
Name: Expensive, Length: 891, dtype: bool

In [226]:
# Sex column को numeric में बदलो (male=0, female=1)।
df['gender_num']=df['Sex'].map({'male':0, 'female':1})
df[['Sex','gender_num']]

        Sex  gender_num
0      male           0
1    female           1
2    female           1
3    female           1
4      male           0
..      ...         ...
886    male           0
887  female           1
888  female           1
889    male           0
890    male           0

[891 rows x 2 columns]

In [228]:
df

     PassengerId  Survived  Pclass                                               Name     Sex  ...  fam  Total_fam  child Expensive  gender_num
0              1         0       3                            Braund, Mr. Owen Harris    male  ...    1          1  False      True           0
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  ...    1          1  False     False           1
2              3         1       3                             Heikkinen, Miss. Laina  female  ...    0          0  False      True           1
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  ...    1          1  False     False           1
4              5         0       3                           Allen, Mr. William Henry    male  ...    0          0  False      True           0
..           ...       ...     ...                                                ...     ...  ...  ...        ...    ...       ...         ...
886          887         0       2                              Montvila, Rev. Juozas    male  ...    0          0  False      True           0
887          888         1       1                       Graham, Miss. Margaret Edith  female  ...    0          0  False      True           1
888          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female  ...    3          3  False      True           1
889          890         1       1                              Behr, Mr. Karl Howell    male  ...    0          0  False      True           0
890          891         0       3                                Dooley, Mr. Patrick    male  ...    0          0  False      True           0

[891 rows x 18 columns]

In [230]:
df.reset_index(drop=True, inplace=True)

In [231]:
df

     PassengerId  Survived  Pclass                                               Name     Sex  ...  fam  Total_fam  child Expensive  gender_num
0              1         0       3                            Braund, Mr. Owen Harris    male  ...    1          1  False      True           0
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  ...    1          1  False     False           1
2              3         1       3                             Heikkinen, Miss. Laina  female  ...    0          0  False      True           1
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  ...    1          1  False     False           1
4              5         0       3                           Allen, Mr. William Henry    male  ...    0          0  False      True           0
..           ...       ...     ...                                                ...     ...  ...  ...        ...    ...       ...         ...
886          887         0       2                              Montvila, Rev. Juozas    male  ...    0          0  False      True           0
887          888         1       1                       Graham, Miss. Margaret Edith  female  ...    0          0  False      True           1
888          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female  ...    3          3  False      True           1
889          890         1       1                              Behr, Mr. Karl Howell    male  ...    0          0  False      True           0
890          891         0       3                                Dooley, Mr. Patrick    male  ...    0          0  False      True           0

[891 rows x 18 columns]

In [ ]:


# 5. Creating / Modifying Columns

# SibSp और Parch मिलाकर total family members वाला column बनाओ।

# Age < 18 वाले passengers के लिए Child column बनाओ, जो True/False दिखाए।

# Fare > 50 वाले passengers के लिए Expensive column बनाओ।

# Sex column को numeric में बदलो (male=0, female=1)।

# 6. Complex / Combined

# Pclass 3 और Age > 40 वाले passengers में से जिन्होंने survived किया, उनके नाम और fare दिखाओ।

# Embarked और Pclass के हिसाब से average fare दिखाओ।

# Sex और Pclass के हिसाब से survival rate (%) निकालो।

# जिन passengers का Cabin missing है, उनकी गिनती निकालो।

# Name में "Mr." या "Mrs." वाले passengers अलग करो।

# Fare और Age दोनों criteria से top 5 passengers दिखाओ।

# SibSp + Parch > 4 वाले passengers का survival rate (%) निकालो।