In [42]:
import numpy as np
import pandas as pd

In [43]:
df=pd.read_csv('anime.csv')

In [44]:
df.loc[4]

Rank                                                     5
Title    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Score                                                 9.05
Name: 4, dtype: object

In [45]:
# process for extracting episodes from the title
def ex_ep(txt):          #we want: (eps 10)
    check=False          #we don't want ..........().......
    d=""                 #we want to add(eps 100) in d
    for i in txt:        #we took i for every word from a txt
        if i=="(":       #when i comes here (
            
            check=True   #start to put data
                         
        if check==True:  #if there is True then start to add charcter
            d+=i         #add in data: eps 10
            
        if i==")":       #add last )
            check=False  #make it False
            return d     #add data in d

In [46]:
# make a new column for episodes
df['Episodes']=df['Title'].apply(ex_ep)

In [47]:
df['Episodes']=df['Episodes'].str.replace(r'\(|\)|\s*eps','',regex=True)

In [48]:
df['Episodes']=df['Episodes'].astype(int)

In [49]:
df.loc[8]['Title']

'Kaguya-sama wa Kokurasetai: Ultra RomanticTV (13 eps)Apr 2022 - Jun 2022851,445 members'

In [50]:
# process for Total_Time to extract from title
import re

def time_stamp(txt):
    # ) ke baad jo pattern month-year - month-year hai, usko match kare
    match = re.search(r'\)\s*([A-Za-z]{3}\s\d{4}\s*-\s*[A-Za-z]{3}\s\d{4})', txt)# ):\)  ' ':\s*  Apr:[A-Za-z]{3}  ' '2016:\s\d{4}  ' ':\s*  -  ' ':\s*
    if match:
        return match.group(1)   # matched date return karo
    return ''

In [61]:
# make a new column for total_time declare
df['Time']=df['Title'].apply(time_stamp)

In [52]:
# process for how many months took for anime
from dateutil import parser
import calendar

# Function to calculate months between two dates
def months_between(txt):
    start_str, end_str = txt.split(' - ')
    start_date = parser.parse(start_str)
    end_date = parser.parse(end_str)
    months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month) + 1
    return months

# Apply function

In [60]:
# make a new column for total_month to take
df['Total_Months'] = df['Time'].apply(months_between)

In [54]:
df[df['Score']==df['Score'].max()]

,Rank,Title,Score,Episodes,Time,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [55]:
# High score first 5 anime
df.sort_values(by='Score',ascending=False).head()

,Rank,Title,Score,Episodes,Time,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [56]:
# maximum episodes
df[df['Episodes']==df['Episodes'].max()]

,Rank,Title,Score,Episodes,Time,Total_Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [57]:
# first 5 highest episodes
df.sort_values(by='Episodes',ascending=False).head()

,Rank,Title,Score,Episodes,Time,Total_Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

In [59]:
# which is longest running anime
df[df['Total_Months']==df['Total_Months'].max()]

,Rank,Title,Score,Episodes,Time,Total_Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111